apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deploytime: {{ now | date "2006-01-02T15:04:05" }}
  creationTimestamp: null
  labels:
    app: ubuntu-deployment-log
  name: ubuntu-deployment-log
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ubuntu-deployment-log
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ubuntu-deployment-log
    spec:
      serviceAccountName: ubuntu-deployment-log
      containers:
      - image: ubuntu:22.04
        name: ubuntu-deployment-log
        command: ['sh', '-c', "sh /start.sh"]
        volumeMounts:
        - name: scripts
          mountPath: /start.sh
          subPath: start.sh
          readOnly: false
    {{- if $.Values.addResourcesRequirements }}
        resources:
          requests:
            cpu: 1
            memory: 100Mi
          limits:
            cpu: 2
            memory: 100Mi
      {{ end -}}
      volumes:
      - name: scripts
        configMap:
          name: deploy-docker-confs


