apiVersion: v1
kind: ServiceAccount
metadata:
  name: ubuntu-deployment-log
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.aws_account_number }}:role/c-eksec2--e-isidoroRoleForPod